name: ND2conversion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyqt
  - numpy
  - pandas
  - tifffile
  - scikit-image
  - opencv
  - tqdm
  - pip
  - math
  - pip:
      - nd2
      - pybis

